- justfile
- package-lock.json
- package.json
- src/mappings/index.ts
- src/types/calls.ts
- src/types/support.ts
- :robot: added update-deps to justfile
- :package: update all dependecies
- :bug: using version 1020 for system.remark
- :top: get new types from chain
> Update to lastest dependencies

- db/migrations/1652365126870-Data.js
- src/mappings/utils/cache.ts
- src/model/generated/series.model.ts
> feat: totalEmotesCount

- schema.graphql
> fix_schema_total_emotes_count

- src/server-extension/model/event.model.ts
- src/server-extension/query/event.ts
- src/server-extension/resolvers/event.ts
- src/server-extension/resolvers/index.ts
WFM
ref:
#29 
https://github.com/kodadot/nft-gallery/issues/3059
> feat: last event resolver

- src/server-extension/model/event.model.ts
- src/server-extension/query/event.ts
Use `group by` to remove duplicate values.
> fix: event group by nft_id

- .github/workflows/subsquid.yml
- add auto deploy/update to subsquid from `release-***` branch pattern
- need to add `DEPLOYMENT_KEY` as GitHub secrets
- tested in https://github.com/preschian/rubick/pull/5/checks
> feat: deploy/update subsquid from gh actions

- src/server-extension/model/emote.model.ts
- src/server-extension/query/emote.ts
- src/server-extension/resolvers/emote.ts
- src/server-extension/resolvers/index.ts
- ':zap: resolver to return map count for each emote'
- ':zap: export emote resolver'
- :poop: fugly code
> Emote API fro Berlin Blockchain Week

- package.json
- add collection in lastEvent query
- run codegen
- revert generated
- :top: :package:
- :bug: changes in typeorm
- :squid: codegen
- :brom: we only care about system.remark
- :bug: migrations
- :robot: prod
- :top: update packages
> New cute packages

- package-lock.json
Rubick is stuck, calling :ambulance:
> :ambulance: broken package-lock

- package-lock.json
- package.json
> :ambulance: broken package

- src/mappings/utils/metadata.ts
related with kodadot/nft-gallery#4610
> 🔧 metadata gateway

- src/mappings/v2/lock.ts
> :zap: collection has lock

- package-lock.json
- package.json
- src/mappings/v2/emote.ts
- :arrow_up: @kodadot1/minimark
- :zap: namespaced rmrk emotes
> 215 very emote

- src/mappings/v2/buy.ts
> 232 Buys with recipient

- package-lock.json
- package.json
- src/mappings/utils/consolidator.ts
- src/mappings/v2/change.ts
- :arrow_up: @kodadot1/minimark
- :label: base is also entity
- :zap: changeissuer also for base
> 223 drop the base

- marck.yaml
- src/mappings/v2/base.ts
- src/mappings/v2/destroy.ts
- src/processor.ts
- :broom: lint
- :bookmark: MARCK V3
> lint before take off

- .github/workflows/subsquid.yml
> :wrench: update squid deploys

- src/mappings/utils/helper.ts
- src/server-extension/model/child.model.ts
- src/server-extension/query/nft.ts
> feat: Add z to childItemEntity

- src/mappings/v2/base.ts
> :bug: no z-slot for fixed parts

- db/migrations/1681329677484-Data.js
- src/mappings/index.ts
> Release v9

- .github/workflows/subsquid.yml
> :green_heart: deploy

- .github/workflows/subsquid.yml
> :green_heart: old squid cli

- package-lock.json
- package.json
- src/mappings/index.ts
- src/mappings/utils/helper.ts
> :wrench: ready to deploy
